AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-lambda-typescript

  Sample SAM Template for aws-sam-lambda-typescript

Globals:
  Function:
    Timeout: 5

Resources:
  ParseRunFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: build/controllers/validateRun.lambdaHandler
      Runtime: nodejs14.x
      Events:
        ValidateRun:
          Type: Api
          Properties:
            Path: /parse-run
            Method: get
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps
